sbatch exp_baseline_RNN.py --DATASET 0 --task temporal --loss celoss --metric acc --LR 0.01 --projectname Baseline
sbatch exp_baseline_RNN.py --DATASET 1 --task temporal --loss celoss --metric acc --LR 0.01 --projectname Baseline
sbatch exp_baseline_RNN.py --DATASET 2 --task temporal --loss celoss --metric acc --LR 0.01 --projectname Baseline
sbatch exp_baseline_RNN.py --DATASET 3 --task temporal --loss celoss --metric acc --LR 0.01 --projectname Baseline
sbatch exp_baseline_RNN.py --DATASET 4 --task temporal --loss celoss --metric acc --LR 0.01 --projectname Baseline
sbatch exp_baseline_RNN.py --DATASET 5 --task temporal --loss celoss --metric acc --LR 0.01 --projectname Baseline
sbatch exp_baseline_RNN.py --DATASET 6 --task temporal --loss celoss --metric acc --LR 0.01 --projectname Baseline
sbatch exp_baseline_RNN.py --DATASET 7 --task temporal --loss celoss --metric acc --LR 0.01 --projectname Baseline
sbatch exp_baseline_RNN.py --DATASET 8 --task temporal --loss celoss --metric acc --LR 0.01 --projectname Baseline
sbatch exp_baseline_RNN.py --DATASET 9 --task temporal --loss celoss --metric acc --LR 0.01 --projectname Baseline
sbatch exp_baseline_RNN.py --DATASET 10 --task temporal --loss celoss --metric acc --LR 0.01 --projectname Baseline
sbatch exp_baseline_RNN.py --DATASET 11 --task temporal --loss celoss --metric acc --LR 0.01 --projectname Baseline
sbatch exp_baseline_RNN.py --DATASET 12 --task temporal --loss celoss --metric acc --LR 0.01 --projectname Baseline
sbatch exp_baseline_RNN.py --DATASET 13 --task temporal --loss celoss --metric acc --LR 0.01 --projectname Baseline
sbatch exp_baseline_RNN.py --DATASET 14 --task temporal --loss celoss --metric acc --LR 0.01 --projectname Baseline
