sbatch exp_LearnableFilters.py --SEED 0 --task temporal --loss celoss --metric temporal_acc --LR 0.001 --projectname LearnableFiltersL2
sbatch exp_LearnableFilters.py --SEED 1 --task temporal --loss celoss --metric temporal_acc --LR 0.001 --projectname LearnableFiltersL2
sbatch exp_LearnableFilters.py --SEED 2 --task temporal --loss celoss --metric temporal_acc --LR 0.001 --projectname LearnableFiltersL2
sbatch exp_LearnableFilters.py --SEED 3 --task temporal --loss celoss --metric temporal_acc --LR 0.001 --projectname LearnableFiltersL2
sbatch exp_LearnableFilters.py --SEED 4 --task temporal --loss celoss --metric temporal_acc --LR 0.001 --projectname LearnableFiltersL2
sbatch exp_LearnableFilters.py --SEED 5 --task temporal --loss celoss --metric temporal_acc --LR 0.001 --projectname LearnableFiltersL2
sbatch exp_LearnableFilters.py --SEED 6 --task temporal --loss celoss --metric temporal_acc --LR 0.001 --projectname LearnableFiltersL2
sbatch exp_LearnableFilters.py --SEED 7 --task temporal --loss celoss --metric temporal_acc --LR 0.001 --projectname LearnableFiltersL2
sbatch exp_LearnableFilters.py --SEED 8 --task temporal --loss celoss --metric temporal_acc --LR 0.001 --projectname LearnableFiltersL2
sbatch exp_LearnableFilters.py --SEED 9 --task temporal --loss celoss --metric temporal_acc --LR 0.001 --projectname LearnableFiltersL2
