sbatch exp_baseline_SNN.py --DATASET 0 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 1 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 2 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 3 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 4 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 5 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 6 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 7 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 8 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 9 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 10 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 11 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 12 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 13 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 14 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 15 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 16 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 17 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 18 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 19 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 20 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 21 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 22 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 23 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 24 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 25 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 26 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 27 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 28 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 29 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 30 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 31 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 32 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 33 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 34 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 35 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 36 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 37 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 38 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 39 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 40 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 41 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 42 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 43 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 44 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 45 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 46 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 47 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 48 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 49 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 50 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 51 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 52 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 53 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 54 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 55 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 56 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 57 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 58 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 59 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 60 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 61 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 62 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 63 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 64 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 65 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 66 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 67 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 68 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 69 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 70 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 71 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 72 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 73 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 74 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 75 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 76 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 77 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 78 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 79 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
