sbatch exp_LearnableFilters.py --DATASET 16 --SEED 0 --task temporal --loss celoss --metric temporal_acc --projectname LearnableFilters
sbatch exp_LearnableFilters.py --DATASET 16 --SEED 1 --task temporal --loss celoss --metric temporal_acc --projectname LearnableFilters
sbatch exp_LearnableFilters.py --DATASET 16 --SEED 2 --task temporal --loss celoss --metric temporal_acc --projectname LearnableFilters
sbatch exp_LearnableFilters.py --DATASET 16 --SEED 3 --task temporal --loss celoss --metric temporal_acc --projectname LearnableFilters
sbatch exp_LearnableFilters.py --DATASET 16 --SEED 4 --task temporal --loss celoss --metric temporal_acc --projectname LearnableFilters
sbatch exp_LearnableFilters.py --DATASET 16 --SEED 5 --task temporal --loss celoss --metric temporal_acc --projectname LearnableFilters
sbatch exp_LearnableFilters.py --DATASET 16 --SEED 6 --task temporal --loss celoss --metric temporal_acc --projectname LearnableFilters
sbatch exp_LearnableFilters.py --DATASET 16 --SEED 7 --task temporal --loss celoss --metric temporal_acc --projectname LearnableFilters
sbatch exp_LearnableFilters.py --DATASET 16 --SEED 8 --task temporal --loss celoss --metric temporal_acc --projectname LearnableFilters
sbatch exp_LearnableFilters.py --DATASET 16 --SEED 9 --task temporal --loss celoss --metric temporal_acc --projectname LearnableFilters
sbatch exp_LearnableFilters.py --DATASET 17 --SEED 0 --task temporal --loss celoss --metric temporal_acc --projectname LearnableFilters
sbatch exp_LearnableFilters.py --DATASET 17 --SEED 1 --task temporal --loss celoss --metric temporal_acc --projectname LearnableFilters
sbatch exp_LearnableFilters.py --DATASET 17 --SEED 2 --task temporal --loss celoss --metric temporal_acc --projectname LearnableFilters
sbatch exp_LearnableFilters.py --DATASET 17 --SEED 3 --task temporal --loss celoss --metric temporal_acc --projectname LearnableFilters
sbatch exp_LearnableFilters.py --DATASET 17 --SEED 4 --task temporal --loss celoss --metric temporal_acc --projectname LearnableFilters
sbatch exp_LearnableFilters.py --DATASET 17 --SEED 5 --task temporal --loss celoss --metric temporal_acc --projectname LearnableFilters
sbatch exp_LearnableFilters.py --DATASET 17 --SEED 6 --task temporal --loss celoss --metric temporal_acc --projectname LearnableFilters
sbatch exp_LearnableFilters.py --DATASET 17 --SEED 7 --task temporal --loss celoss --metric temporal_acc --projectname LearnableFilters
sbatch exp_LearnableFilters.py --DATASET 17 --SEED 8 --task temporal --loss celoss --metric temporal_acc --projectname LearnableFilters
sbatch exp_LearnableFilters.py --DATASET 17 --SEED 9 --task temporal --loss celoss --metric temporal_acc --projectname LearnableFilters
