sbatch exp_baseline_pNN.py --SEED 0 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --SEED 1 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --SEED 2 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --SEED 3 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --SEED 4 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --SEED 5 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --SEED 6 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --SEED 7 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --SEED 8 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --SEED 9 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
