sbatch exp_baseline_pNN.py --DATASET 0 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --DATASET 1 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --DATASET 2 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --DATASET 3 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --DATASET 4 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --DATASET 5 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --DATASET 6 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --DATASET 7 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --DATASET 8 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --DATASET 9 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --DATASET 10 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --DATASET 11 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --DATASET 12 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --DATASET 13 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --DATASET 14 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --DATASET 15 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --DATASET 16 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --DATASET 17 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --DATASET 18 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --DATASET 19 --task temporal --loss temporal --metric temporized_acc --projectname Baseline
sbatch exp_baseline_pNN.py --DATASET 19 --task temporal --loss temporal --metric temporized_acc --projectname Baseline