sbatch exp_baseline_SNN.py --DATASET 0 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 1 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 2 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 3 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 4 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 5 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 6 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 7 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 8 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 9 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 10 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 11 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 12 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 13 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
sbatch exp_baseline_SNN.py --DATASET 14 --task temporal --loss temporal --metric nominal_snn --projectname Baseline
