sbatch exp_baseline_SNN.py --SEED 0 --task temporal --loss temporal --metric temporal_acc --projectname Baseline
sbatch exp_baseline_SNN.py --SEED 1 --task temporal --loss temporal --metric temporal_acc --projectname Baseline
sbatch exp_baseline_SNN.py --SEED 2 --task temporal --loss temporal --metric temporal_acc --projectname Baseline
sbatch exp_baseline_SNN.py --SEED 3 --task temporal --loss temporal --metric temporal_acc --projectname Baseline
sbatch exp_baseline_SNN.py --SEED 4 --task temporal --loss temporal --metric temporal_acc --projectname Baseline
sbatch exp_baseline_SNN.py --SEED 5 --task temporal --loss temporal --metric temporal_acc --projectname Baseline
sbatch exp_baseline_SNN.py --SEED 6 --task temporal --loss temporal --metric temporal_acc --projectname Baseline
sbatch exp_baseline_SNN.py --SEED 7 --task temporal --loss temporal --metric temporal_acc --projectname Baseline
sbatch exp_baseline_SNN.py --SEED 8 --task temporal --loss temporal --metric temporal_acc --projectname Baseline
sbatch exp_baseline_SNN.py --SEED 9 --task temporal --loss temporal --metric temporal_acc --projectname Baseline
